/**
 * Output Validator.
 * Prevents invalid data or malicious code (like XSS) from entering the database
 * by validating AI-generated modules strictly.
 */

// Basic structure of a task as defined in our application
interface GeneratedTask {
  title: string;
  description?: string;
  type?: string;
  timeEstimate?: number;
}

// Basic structure of a challenge module generated by AI
export interface GeneratedModule {
  challenge: {
    title: string;
    description: string;
    duration: number;
    goalType: string;
    difficulty: number;
  };
  tasks: GeneratedTask[];
}

export interface OutputValidationResult<T> {
  valid: boolean;
  data?: T;
  error?: string;
}

/** Check if a string contains potentially malicious script or HTML tag injection. */
function containsMaliciousContent(str: string): boolean {
  if (!str) return false;
  // Look for any traces of script tags, javascript protocols, etc.
  const XSS_PATTERNS = [
    /<script/i,
    /javascript:/i,
    /onload\s*=/i,
    /onerror\s*=/i,
    /onmouseover\s*=/i,
    /<iframe/i,
  ];
  return XSS_PATTERNS.some((pattern) => pattern.test(str));
}

/**
 * Deep check all string properties of an object to ensure no XSS patterns exist.
 */
function isSafeStructure(obj: any): boolean {
  if (obj === null || obj === undefined) return true;
  if (typeof obj === "string") return !containsMaliciousContent(obj);
  if (Array.isArray(obj)) return obj.every(isSafeStructure);
  if (typeof obj === "object") {
    return Object.values(obj).every(isSafeStructure);
  }
  return true;
}

/**
 * Validates the AI-generated JSON module against our expected schema.
 * Ensures data integrity before saving to local storage.
 */
export function validateGeneratedModule(
  jsonText: string
): OutputValidationResult<GeneratedModule> {
  let parsed: any;

  try {
    // LLMs sometimes wrap responses in markdown, clean it before parsing
    const cleanJson = jsonText.replace(/^```json\s*/i, "").replace(/\s*```$/i, "").trim();
    parsed = JSON.parse(cleanJson);
  } catch (error) {
    return {
      valid: false,
      error: "Odpověď od AI není validní JSON.",
    };
  }

  // 1. Basic Type Structure Validation
  if (!parsed || typeof parsed !== "object") {
    return { valid: false, error: "Vygenerovaná struktura není platný objekt." };
  }

  if (!parsed.challenge || typeof parsed.challenge !== "object") {
    return { valid: false, error: "Chybí definice výzvy (challenge)." };
  }

  if (!Array.isArray(parsed.tasks)) {
    return { valid: false, error: "Úkoly(tasks) musí být pole (array)." };
  }

  // Challenge specifics
  const c = parsed.challenge;
  if (typeof c.title !== "string" || c.title.trim().length === 0) {
    return { valid: false, error: "Výzva musí mít neprázdný název(title)." };
  }
  if (typeof c.description !== "string" || c.description.trim().length === 0) {
    return { valid: false, error: "Výzva musí mít neprázdný popis(description)." };
  }
  if (typeof c.duration !== "number" || c.duration <= 0) {
    return { valid: false, error: "Trvání (duration) musí být kladné číslo." };
  }

  // Tasks specifics
  for (const t of parsed.tasks) {
    if (typeof t.title !== "string" || t.title.trim().length === 0) {
        return { valid: false, error: "Každý úkol musí mít název(title)." };
    }
  }

  // 2. Security / XSS Validation
  if (!isSafeStructure(parsed)) {
    return {
      valid: false,
      error: "Z bezpečnostních důvodů byla generace zamítnuta (detekován nebezpečný kód).",
    };
  }

  return { valid: true, data: parsed as GeneratedModule };
}
